### PR TITLE
update Stage Edit page

### PR DESCRIPTION
**Pull request by yue-l**
added warning message for stage edit page.
from now on, 'Save Stage' function will inform the risk of media synchronization.
for further details, please refer to each commit

### CODE REVIEW

**Comment by yue-l** [comment]
wondering if we put a warning message on save stage function shall reduce the chances of different media display to different users on a stage..

**Comment by rohrlach** [comment]
Personally, I'd tell twisted to send out a 'Reload' command to connected clients and have the client automatically reload (Perhaps with an explanation as to why whilst it loads)

**Comment by vickis** [comment]
great idea - this neatly avoids the issue of people opting not to reload and therefore having such a different experience (eg not seeing the avatar which is speaking on stage if they have enetered after - as with in the student meetings

kia pai to ra
vicki ("

**Comment by helenvarley** [comment]
but wait, we have discussed this, & that is why there are now two "save" buttons - one being "save and reload" and the other just being "save". this means that when you save a stage, you have the choice to force reload for everyone, or not. this is because during workshops and rehearsals, there can often be several people making changes at the same time, & if the stage is constantly reloading it's quite frustrating. it's better if everyone can do their uploading & then there is one reload.
however, the 2 buttons on the stage edit page still don't really solve this, as when you upload individual media items and assign them to a stage, it forces a reload ...

**Comment by rohrlach** [comment]
Then perhaps we give the client some smarts reload the media and meta data attached to it silently?

**Comment by helenvarley** [comment]
sounds interesting - how would that work? :)

**Comment by rohrlach** [comment]
Well... (In a very basic sense) the client needs to be refactored (I'm not sure how much work this will entail) such that it supports an asset pipeline.  Then it's a matter of having the stage configuration save event broadcast to all connected clients on that stage that there is new media and deliver it.

**Comment by helenvarley** [comment]
that sounds like it could be UpStage v4, or the New UpStage ... ? 
or is it something simple? ;)

**Comment by rohrlach** [comment]
Should be easy :)
HINT: It already does this with MP3s... This is how we have voices

**Comment by helenvarley** [comment]
ok, then it can be an interesting challenge for the new team :)
it would certainly be a great thing if the stage didn't have to reload, it would mean that media could actually be added on the fly ...

**Comment by yue-l** [comment]
I initially thought an instant remedy: to give a warning message of the risk during Save Stage. As I'm aware of users doing things differently, especially for new UpStage developers. I intend to reduce the confusion so that people at least are aware the defects.

**Comment by helenvarley** [comment]
yes, a warning message is definitely good with the way it is now! :)

**Pull request merged**
